#!/bin/bash
if [ -z $1 ]
then 
echo "Не введено имя файла"
exit
fi

if [ -z $2 ]
then 
echo "Не введено расширение файла"
exit
fi

echo "Старое имя файла: "$1

newNameFile=${1%.*}.$2

mv  "$1" "$newNameFile"

echo "Новое имя файла: "$newNameFile